// src/features/conferences/ConferenceCard.tsx
import * as React from "react";
import { Link } from "react-router";

import type { HTConference } from "@/types/db";

import { formatDateRange, toDate, tzAbbrev } from "@/lib/utils/dates";
import { conferencePath } from "@/lib/utils/routes";

export const ConferenceCard = React.memo(function ConferenceCard({
  conference,
  updatedAt,
}: {
  conference: HTConference;
  updatedAt?: Date;
}) {
  const start = toDate(conference.start_timestamp) ?? toDate(conference.start_date);
  const end = toDate(conference.end_timestamp) ?? toDate(conference.end_date);
  const range = formatDateRange(start, end, conference.timezone);
  const tz = tzAbbrev(conference.timezone);
  const updatedLabel = updatedAt
    ? new Intl.DateTimeFormat(undefined, {
        month: "short",
        day: "numeric",
        year: "numeric",
      }).format(updatedAt)
    : undefined;

  return (
    <Link
      to={conferencePath(conference.code)}
      className="ui-focus-ring group block h-full rounded-[0.875rem] focus-visible:outline-none"
    >
      <article className="ui-card ui-card-interactive flex h-full min-h-[7.25rem] flex-col p-5 transition group-hover:shadow-md">
        <h3
          className="line-clamp-2 min-h-[2.75rem] text-lg leading-snug font-semibold break-words text-neutral-100 transition-colors group-hover:text-white"
          title={conference.name}
        >
          {conference.name}
        </h3>

        {(range || tz) && (
          <p className="mt-3 flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1 text-xs font-medium text-neutral-300">
            {range && <time>{range}</time>}
            {range && tz && <span aria-hidden="true">•</span>}
            {tz && <span className="uppercase">{tz}</span>}
          </p>
        )}

        {updatedAt && updatedLabel && (
          <p className="mt-2 text-xs font-medium text-neutral-500">
            Updated <time dateTime={updatedAt.toISOString()}>{updatedLabel}</time>
          </p>
        )}
      </article>
    </Link>
  );
});

// src/components/ConferenceCard.vue
<script setup lang="ts">
import { computed } from "vue";

import type { Conference } from "../types/hackertracker";

import { formatDateRange, timeZoneAbbreviation, toDate } from "../lib/dates";
import { conferencePath } from "../lib/routes";

const props = defineProps<{ conference: Conference; updatedAt?: Date }>();
const start = computed(
  () => toDate(props.conference.start_timestamp) ?? toDate(props.conference.start_date),
);
const end = computed(
  () => toDate(props.conference.end_timestamp) ?? toDate(props.conference.end_date),
);
const range = computed(() => formatDateRange(start.value, end.value, props.conference.timezone));
const zone = computed(() => timeZoneAbbreviation(props.conference.timezone, start.value));
const updatedLabel = computed(() =>
  props.updatedAt
    ? new Intl.DateTimeFormat(undefined, {
        month: "short",
        day: "numeric",
        year: "numeric",
      }).format(props.updatedAt)
    : undefined,
);
</script>

<template>
  <RouterLink :to="conferencePath(conference.code)" class="conference-card-link focus-ring">
    <article class="card interactive conference-card">
      <h3 :title="conference.name">{{ conference.name }}</h3>
      <p v-if="range || zone" class="conference-meta">
        <time v-if="range">{{ range }}</time
        ><span v-if="range && zone" aria-hidden="true">•</span><span v-if="zone">{{ zone }}</span>
      </p>
      <p v-if="updatedAt && updatedLabel" class="updated-at">
        Updated <time :datetime="updatedAt.toISOString()">{{ updatedLabel }}</time>
      </p>
    </article>
  </RouterLink>
</template>

<style scoped>
.conference-card-link {
  display: block;
  height: 100%;
  border-radius: var(--radius-2);
  text-align: left;
}

.conference-card {
  display: flex;
  min-height: 7.25rem;
  height: 100%;
  flex-direction: column;
  border-radius: var(--radius-2);
  padding: 1rem;
  box-shadow: none;
}

h3 {
  display: -webkit-box;
  overflow: hidden;
  min-height: 2.75rem;
  color: var(--text-primary);
  font-size: 1.05rem;
  line-height: 1.35;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
}

.conference-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 0.4rem;
  margin-top: 0.75rem;
  color: var(--text-muted);
  font-size: 0.75rem;
  font-weight: 600;
}

.updated-at {
  margin-top: 0.4rem;
  color: var(--text-subtle);
  font-size: 0.72rem;
}
</style>
